// Generated by gir (https://github.com/gtk-rs/gir @ c0ef822cedca)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 6d1aaead565c)
// DO NOT EDIT

#[cfg(not(feature = "dox"))]
use std::process;

#[cfg(feature = "dox")]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(feature = "dox"))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
